
 const hymns = [
    { number: 317, title: "A CHARGE TO KEEP I HAVE.", lyrics: "" },
    { number: 279, title: "A CHILD OF THE KING!", lyrics: "" },
    { number: 525, title: "A CHRISTIAN HOME.", lyrics: "" },
    { number: 391, title: "A FLAG TO FOLLOW", lyrics: "" },
    { number: 494, title: "A Friend I have called Jesus", lyrics: "" },
    { number: 184, title: "A GLORIOUS CHURCH", lyrics: "" },
    { number: 36,  title: "A MIGHTY FORTRESS IS OUR GOD.", lyrics: "" },
    { number: 306, title: "A PASSION FOR SOULS..", lyrics: "" },
    { number: 292, title: "A pilgrim was I, and awand'ring....", lyrics: "" },
    { number: 194, title: "A ruler once came to Jesus by night.", lyrics: "" },
    { number: 263, title: "A SHELTER IN THE TIME OF STORM.", lyrics: "" },
    { number: 406, title: "A soldier in the army of the King of", lyrics: "" },
    { number: 324, title: "A STUDENT'S PRAYER", lyrics: "" },
    { number: 258, title: "A wonderful Savior is Jesus my Lord", lyrics: "" },
    { number: 75,  title: "ABIDE WITH ME", lyrics: "" },
    { number: 192, title: "ACCORDING TO THY GRACIOUS WORD", lyrics: "" },
    { number: 501, title: "AFTER", lyrics: "" },
    { number: 129, title: "Alas! and did my Savior (Hudson)", lyrics: "" },
    { number: 110, title: "ALAS! AND DID MY SAVIOR (Wilson)", lyrics: "" },
    { number: 31, title: "ALL CREATURES OF OUR GOD AND KING", lyrics: "" },
    { number: 386, title: "ALL FOR JESUS", lyrics: "" },
    { number: 108, title: "ALL GLORY, LAUD AND HONOR", lyrics: "" },
    { number: 47, title: "ALL GLORY TO JESUS", lyrics: "" },
    { number: 42, title: "ALL HAIL THE POWER (Holden)..", lyrics: "" },
    { number: 43, title: "ALL HAIL THE POWER (Shrubsole).", lyrics: "" },
    { number: 446, title: "All my life long I had panted", lyrics: "" },
    { number: 8, title: "ALL PEOPLE THAT ON EARTH DO DWELL", lyrics: "" },
    { number: 463, title: "ALL THAT THRILLS MY SOUL", lyrics: "" },
    { number: 296, title: "ALL THE WAY MY SAVIOR LEADS ME.", lyrics: "" },
    { number: 537, title: "ALL THINGS COME OF THEE..", lyrics: "" },
    { number: 267, title: "ALL THINGS WORK OUT FOR GOOD.", lyrics: "" },
    { number: 394, title: "All to Jesus I surrender.", lyrics: "" },
    { number: 536, title: "ALMIGHTY FATHER, HEAR OUR PRAYER.", lyrics: "" },
    { number: 251, title: "ALMOST PERSUADED", lyrics: "" },
    { number: 414, title: "AM I A SOLDIER OF THE CROSS?", lyrics: "" },
    { number: 236, title: "AMAZING GRACE", lyrics: "" },
    { number: 1000, title: "AMENS", lyrics: "" },
    { number: 529, title: "AMERICA", lyrics: "" },
    { number: 531, title: "AMERICA THE BEAUTIFUL", lyrics: "" },
    { number: 22, title: "ANCIENT OF DAYS", lyrics: "" },
    { number: 44, title: "AND CAN IT BE THAT I SHOULD GAIN?", lyrics: "" },
    { number: 99, title: "ANGELS, FROM THE REALMS OF GLORY", lyrics: "" },
    { number: 89, title: "ANGELS WE HAVE HEARD ON HIGH.", lyrics: "" },
    { number: 520, title: "ANOTHER YEAR IS DAWNING", lyrics: "" },
    { number: 422, title: "ANYWHERE WITH JESUS", lyrics: "" },
    {number: 365, title: "\"ARE YE ABLE,\" SAID THE MASTER", lyrics: "" },
    {number: 208, title: "ARE YOU WASHED IN THE BLOOD?", lyrics: ""},
    {number: 223, title: "ARISE, MY SOUL, ARISE!", lyrics: ""},
    {number: 239, title: "ART THOU WEARY?", lyrics: ""},
    {number: 96, title: "AS WITH GLADNESS MEN OF OLD.", lyrics: ""},
    {number: 477, title: "AT CALVARY", lyrics: ""},
    {number: 129, title: "AT THE CROSS.", lyrics: ""},
    {number: 9, title: "Awake, my soul, to joyful lays", lyrics: ""},
    {number: 86, title: "AWAY IN A MANGER", lyrics: ""},
    {number: 530, title: "BATTLE HYMN OF THE REPUBLIC", lyrics: ""},
    {number: 290, title: "BE STILL, MY SOUL", lyrics: ""},
    {number: 334, title: "BE THOU MY VISION", lyrics: ""},
    {number: 50, title: "Beautiful Savior", lyrics: "", see: 50},
    {number: 5, title: "BEGIN, MY TONGUE, SOME HEAVENLY", lyrics: ""},
    {number: 309, title: "BENEATH THE CROSS OF JESUS", lyrics: ""},
    {number: 1000, title: "BENEDICTION", lyrics: "", backCover: true},
    {number: 515, title: "BEULAH LAND", lyrics: ""},
    {number: 30, title: "BLESS THE LORD", lyrics: ""},
    {number: 255, title: "BLESSED ASSURANCE", lyrics: ""},
    {number: 196, title: "BLESSED BE THE FOUNTAIN", lyrics: ""},
    {number: 32, title: "BLESSED BE THE NAME", lyrics: ""},
    {number: 121, title: "BLESSED CALVARY!", lyrics: ""},
    {number: 71, title: "BLESSED DAY OF REST AND CHEER", lyrics: ""},
    {number: 345, title: "Blessed hour of prayer.", lyrics: ""},
    {number: 159, title: "BLESSED QUIETNESS", lyrics: ""},
    {number: 112, title: "BLESSED REDEEMER", lyrics: ""},
    {number: 187, title: "BLEST BE THE TIE THAT BINDS..", lyrics: ""},
    {number: 102, title: "Born among cattle, in poverty sore.", lyrics: ""},
    {number: 176, title: "BREAK THOU THE BREAD OF LIFE", lyrics: ""},
    {number: 164, title: "BREATHE ON ME, BREATH OF GOD..", lyrics: ""},
    {number: 15, title: "BRETHREN, WE HAVE MET TO WORSHIP..", lyrics: ""},
    {number: 371, title: "Brightly beams our Father's mercy", lyrics: ""},
    {number: 436, title: "BRING THEM IN", lyrics: ""},
    {number: 382, title: "Bring ye all the tithes into the store", lyrics: ""},
    {number: 420, title: "BRINGING IN THE SHEAVES", lyrics: ""},
    {number: 218, title: "BURDENS ARE LIFTED AT CALVARY", lyrics: ""},
    {number: 160, title: "CHANNELS ONLY", lyrics: ""},
    {number: 300, title: "Children of the heavenly Father", lyrics: "", see: 300},
    {number: 138, title: "CHRIST AROSE", lyrics: ""},
    {number: 136, title: "CHRIST IS RISEN FROM THE DEAD.", lyrics: ""},
    {number: 466, title: "CHRIST LIVETH IN ME", lyrics: ""},
    {number: 232, title: "Christ our Redeemer died on the cross", lyrics: ""},
    {number: 199, title: "CHRIST RECEIVETH SINFUL MEN.", lyrics: ""},
    {number: 156, title: "CHRIST RETURNETH!", lyrics: ""},
    {number: 137, title: "CHRIST THE LORD IS RISEN TODAY", lyrics: ""},
    {number: 166, title: "CLEANSE ME", lyrics: ""},
    {number: 328, title: "CLOSE TO THEE", lyrics: ""},
    {number: 55, title: "COME, CHRISTIANS, JOIN TO SING", lyrics: ""},
    {number: 252, title: "Come, ev'ry soul by sin oppressed", lyrics: ""},
    {number: 158, title: "COME, HOLY SPIRIT, HEAVENLY DOVE", lyrics: ""},
    {number: 6, title: "COME, THOU ALMIGHTY KING", lyrics: ""},
    {number: 17, title: "COME, THOU FOUNT", lyrics: ""},
    {number: 84, title: "COME, THOU LONG-EXPECTED JESUS", lyrics: ""},
    {number: 254, title: "COME TO THE SAVIOR", lyrics: ""},
    {number: 514, title: "Come, we that love the Lord (Lowry)", lyrics: ""},
    {number: 23, title: "COME, WE THAT LOVE THE (Williams)", lyrics: ""},
    {number: 286, title: "COME, YE DISCONSOLATE", lyrics: ""},
    {number: 526, title: "COME, YE THANKFUL PEOPLE", lyrics: ""},
    {number: 151, title: "Coming again, coming again.", lyrics: ""},
    {number: 411, title: "Conquering now and still to conquer", lyrics: ""},
    {number: 478, title: "CONSTANTLY ABIDING", lyrics: ""},
    {number: 370, title: "COUNT YOUR BLESSINGS..", lyrics: ""},
    {number: 62, title: "CROWN HIM WITH MANY CROWNS", lyrics: ""},
   /* {number: null, title: "DARE TO BE A DANIEL", lyrics: ""},
    {number: null, title: "DAY BY DAY.", lyrics: ""},
    {number: null, title: "DAY IS DYING IN THE WEST", lyrics: ""},
    {number: null, title: "DEAR LORD AND FATHER OF MANKIND", lyrics: ""},
    {number: null, title: "DEEPER AND DEEPER DEPTH OF MERCY", lyrics: ""},
    {number: null, title: "DOES JESUS CARE?", lyrics: ""},
    {number: null, title: "Down at the cross where my Savior died", lyrics: ""},
    {number: null, title: "Down in the valley with my Savior", lyrics: ""},
    {number: null, title: "DOXOLOGY", lyrics: ""},
    {number: null, title: "Draw me nearer, nearer, blessed Lord", lyrics: ""},
    {number: null, title: "Drinking at the springs of living water", lyrics: ""},
    {number: null, title: "Dying with Jesus by death reckoned mine", lyrics: ""},
    {number: null, title: "Encamped along the hills of light.", lyrics: ""},
    {number: null, title: "EVEN ME", lyrics: ""},
    {number: null, title: "FACE TO FACE", lyrics: ""},
    {number: null, title: "FADE, FADE, EACH EARTHLY JOY", lyrics: ""},
    {number: null, title: "FAIREST LORD JESUS", lyrics: ""},
    {number: null, title: "FAITH Is THE VICTORY.", lyrics: ""},
    {number: null, title: "FAITH OF OUR FATHERS", lyrics: ""},
    {number: null, title: "Far and near the fields are teeming", lyrics: ""},
    {number: null, title: "Far away in the depths of my spirit", lyrics: ""},
    {number: null, title: "Far, far away, in heathen darkness", lyrics: ""},
    {number: null, title: "Fierce and wild the storm is raging", lyrics: ""},
    {number: null, title: "FIGHT THE GOOD FIGHT", lyrics: ""},
    {number: null, title: "FILL ALL MY VISION.", lyrics: ""},
    {number: null, title: "FILL ME NOW", lyrics: ""},
    {number: null, title: "FOLLOW, I WILL FOLLOW THEE", lyrics: ""},
    {number: null, title: "FOLLOW ON", lyrics: ""},
    {number: null, title: "FOOTSTEPS OF JESUS", lyrics: ""},
    {number: null, title: "FOR ALL THE SAINTS", lyrics: ""},
    {number: null, title: "FOR GOD SO LOVED THE WORLD", lyrics: ""},
    {number: null, title: "FOR THE BEAUTY OF THE EARTH", lyrics: ""},
    {number: null, title: "For you I am praying", lyrics: ""},
    {number: null, title: "Free from the law-O happy condition", lyrics: ""},
    {number: null, title: "FROM EVERY STORMY WIND THAT BLOWS", lyrics: ""},
    {number: null, title: "FROM GREENLAND'S ICY MOUNTAINS", lyrics: ""},
    {number: null, title: "From over hill and plain there comes", lyrics: ""},
    {number: null, title: "Give me a passion for souls, dear Lord", lyrics: ""},
    {number: null, title: "GIVE ME THY HEART", lyrics: ""},
    {number: null, title: "GIVE OF YOUR BEST TO THE MASTER", lyrics: ""},
    {number: null, title: "Gloria in excelsis Deo!", lyrics: ""},
    {number: null, title: "GLORIA PATRI", lyrics: ""},
    {number: null, title: "GLORIOUS THINGS OF THEE ARE SPOKEN", lyrics: ""},
    {number: null, title: "GLORY BE TO THE FATHER", lyrics: ""},
    {number: null, title: "GLORY TO HIS NAME", lyrics: ""},
    {number: null, title: "GO TELL UNTOLD MILLIONS", lyrics: ""},
    {number: null, title: "GO YE INTO ALL THE WORLD", lyrics: ""},
    {number: null, title: "GOD BE WITH YOU.", lyrics: ""},
    {number: null, title: "GOD INCARNATE, JESUS CAME", lyrics: ""},
    {number: null, title: "GOD LEADS US ALONG", lyrics: ""},
    {number: null, title: "GOD OF EVERLASTING GLORY", lyrics: ""},
    {number: null, title: "GOD OF OUR FATHERS", lyrics: ""},
    {number: null, title: "GOD OF OUR YOUTH", lyrics: ""},
    {number: null, title: "God, the all-wise, and Creator", lyrics: ""},
    {number: null, title: "GOD WILL TAKE CARE OF YOU", lyrics: ""},
    {number: null, title: "GOD's FINAL CALL", lyrics: ""},
    {number: null, title: "GOLDEN HARPS ARE SOUNDING", lyrics: ""},
    {number: null, title: "GRACE GREATER THAN OUR SIN", lyrics: ""},
    {number: null, title: "GRACE! 'TIS A CHARMING SOUND", lyrics: ""},
    {number: null, title: "GRACIOUS SAVIOR, WHO DIDST HONOR", lyrics: ""},
    {number: null, title: "GREAT GOD OF WONDERS!", lyrics: ""},
    {number: null, title: "GREAT GOD, WE SING THAT MIGHTY", lyrics: ""},
    {number: null, title: "GREAT IS THY FAITHFULNESS", lyrics: ""},
    {number: null, title: "GUIDE ME, O THOU GREAT JEHOVAH", lyrics: ""},
    {number: null, title: "HAIL, THOU ONCE-DESPISED JESUS!", lyrics: ""},
    {number: null, title: "HAIL TO THE BRIGHTNESS", lyrics: ""},
    {number: null, title: "HALLELUJAH FOR THE CROSS! 211", lyrics: ""},
    {number: null, title: "HALLELUJAH, 'TIs DONE! 197", lyrics: ""},
    {number: null, title: "HALLELUJAH, WHAT A SAVIOR! 127", lyrics: ""},
    {number: null, title: "HAPPY THE HOME WHEN GOD IS THERE 523", lyrics: ""},
    {number: null, title: "HARK! TEN THOUSAND HARPS AND VOICES 144", lyrics: ""},
    {number: null, title: "HARK! THE HERALD ANGELS SING 93", lyrics: ""},
    {number: null, title: "Hark! 'tis the Shepherd's voice I hear 436", lyrics: ""},
    {number: null, title: "HAVE I DONE MY BEST FOR JESUS? 368", lyrics: ""},
    {number: null, title: "HAVE THINE OWN WAY 388", lyrics: ""},
    {number: null, title: "HAVE YOU ANY ROOM FOR JESUS? 241", lyrics: ""},
    {number: null, title: "HE HIDETH MY SOUL 258", lyrics: ""},
    {number: null, title: "HE IS ABLE TO DELIVER THEE 201", lyrics: ""},
    {number: null, title: "HE Is COMING AGAIN 155", lyrics: ""},
    {number: null, title: "HE IS SO PRECIOUS TO ME 456", lyrics: ""},
    {number: null, title: "HE KEEPS ME SINGING. 453", lyrics: ""},
    {number: null, title: "HE LEADETH ME 295", lyrics: ""},
    {number: null, title: "HE LIFTED ME . 459", lyrics: ""},
    {number: null, title: "HE LIVES 132", lyrics: ""},
    {number: null, title: "HE RANSOMED ME 445", lyrics: ""},
    {number: null, title: "HE THE PEARLY GATES WILL OPEN 513", lyrics: ""},
    {number: null, title: "HE WAS WOUNDED FOR OUR TRANSGRESSIONS 117", lyrics: ""},
    {number: null, title: "HEAR OUR PRAYER, O LORD 535", lyrics: ""},
    {number: null, title: "HEAVEN CAME DOWN AND GLORY FILLED 473", lyrics: ""},
    {number: null, title: "HEAVENLY JOY IS RINGING 491", lyrics: ""},
    {number: null, title: "HEAVENLY SUNLIGHT 472", lyrics: ""},
    {number: null, title: "HERE, O MY LORD, I SEE THEE FACE TO FACE 191", lyrics: ""},
    {number: null, title: "HIDING IN THEE 282", lyrics: ""},
    {number: null, title: "HIGHER GROUND 308", lyrics: ""},
    {number: null, title: "HIS LOVING-KINDNESS 9", lyrics: ""},
    {number: null, title: "HIs MATCHLESS WORTH", lyrics: ""},
    {number: null, title: "HIS WAY WITH THEE", lyrics: ""},
    {number: null, title: "HOLD THE FORT", lyrics: ""},
    {number: null, title: "HOLY BIBLE, BOOK DIVINE", lyrics: ""},
    {number: null, title: "HOLY GHOST, WITH LIGHT DIVINE", lyrics: ""},
    {number: null, title: "HOLY GOD, WE PRAISE THY NAME", lyrics: ""},
    {number: null, title: "HOLY, HOLY, HOLY", lyrics: ""},
    {number: null, title: "HOLY SPIRIT, FAITHFUL GUIDE", lyrics: ""},
    {number: null, title: "HOLY SPIRIT, LIGHT DIVINE", lyrics: ""},
    {number: null, title: "HOMESICK FOR HEAVEN", lyrics: ""},
    {number: null, title: "HOSANNA, LOUD HOSANNA!", lyrics: ""},
    {number: null, title: "HOW BEAUTIFUL HEAVEN MUST BE", lyrics: ""},
    {number: null, title: "How can I fear with Jesus near?", lyrics: ""},
    {number: null, title: "HOW FIRM A FOUNDATION", lyrics: ""},
    {number: null, title: "HOW GREAT THOU ART", lyrics: ""},
    {number: null, title: "HOW HAPPY ARE THEY WHO THEIR SAVIOR", lyrics: ""},
    {number: null, title: "HOW SWEET THE NAME OF JESUS SOUNDS", lyrics: ""},
    {number: null, title: "I AM A POOR WAYFARING STRANGER", lyrics: ""},
    {number: null, title: "I AM COMING, LORD", lyrics: ""},
    {number: null, title: "I AM PRAYING FOR YOU", lyrics: ""},
    {number: null, title: "I AM RESOLVED", lyrics: ""},
    {number: null, title: "I am so glad that our Father in Heav", lyrics: ""},
    {number: null, title: "I AM THINE, O LORD", lyrics: ""},
    {number: null, title: "I AM TRUSTING THEE, LORD JESUS", lyrics: ""},
    {number: null, title: "I ASKED THE LORD", lyrics: ""},
    {number: null, title: "I BELIEVE IN MIRACLES", lyrics: ""},
    {number: null, title: "I BRING MY SINS TO THEE", lyrics: ""},
    {number: null, title: "I CAN, I WILL, I DO BELIEVE", lyrics: ""},
    {number: null, title: "I COME TO THE GARDEN ALONE", lyrics: ""},
    {number: null, title: "I COULD NOT DO WITHOUT THEE", lyrics: ""},
    {number: null, title: "I COULD NOT DO WITHOUT YOU", lyrics: ""},
    {number: null, title: "I DO BELIEVE", lyrics: ""},
    {number: null, title: "I DON'T KNOW ABOUT TOMORROW", lyrics: ""},
    {number: null, title: "I FEEL LIKE TRAVELING ON", lyrics: ""},
    {number: null, title: "I GAVE MY LIFE FOR THEE", lyrics: ""},
    {number: null, title: "I HAVE A FATHER", lyrics: ""},
    {number: null, title: "I have a song that Jesus gave me", lyrics: ""},
    {number: null, title: "I HAVE DECIDED TO FOLLOW JESUS", lyrics: ""},
    {number: null, title: "I HAVE FOUND A FRIEND IN JESUS", lyrics: ""},
    {number: null, title: "I HAVE HEARD OF A LAND", lyrics: ""},
    {number: null, title: "I HAVE LEARNED TO TRUST IN JESUS", lyrics: ""},
    {number: null, title: "I HAVE NO REGRETS", lyrics: ""},
    {number: null, title: "I KNOW A FOUNT", lyrics: ""},
    {number: null, title: "I KNOW HE HEARD MY PRAYER.", lyrics: ""},
    {number: null, title: "I KNOW THE LORD WILL FIND A WAY", lyrics: ""},
    {number: null, title: "I KNOW WHOM I HAVE BELIEVED", lyrics: ""},
    {number: null, title: "I LOVE TO TELL THE STORY", lyrics: ""},
    {number: null, title: "I LOVE YOU, LORD", lyrics: ""},
    {number: null, title: "I MUST TELL JESUS", lyrics: ""},
    {number: null, title: "I NEED THEE EVERY HOUR", lyrics: ""},
    {number: null, title: "I SHALL KNOW HIM", lyrics: ""},
    {number: null, title: "I SURRENDER ALL", lyrics: ""},
    {number: null, title: "I UNDERSTAND THE SAVIOR", lyrics: ""},
    {number: null, title: "I WAS A WANDERING SHEEP", lyrics: ""},
    {number: null, title: "I WAS GLAD WHEN THEY SAID UNTO ME", lyrics: ""},
    {number: null, title: "I WILL BLESS THE LORD", lyrics: ""},
    {number: null, title: "I WILL FOLLOW JESUS", lyrics: ""},
    {number: null, title: "I WILL MAKE YOU FISHERS OF MEN", lyrics: ""},
    {number: null, title: "I WILL PRAISE HIM", lyrics: ""},
    {number: null, title: "I WILL SING THE WONDROUS STORY", lyrics: ""},
    {number: null, title: "I WILL SING THE WONDROUS STORY", lyrics: ""},
    {number: null, title: "I WILL SING YOU A SONG", lyrics: ""},*/
];


function searchHymn() {
    const searchTerm = document.getElementById('searchInput').value.toLowerCase().trim();
    const searchResults = document.getElementById('searchResults');
    searchResults.innerHTML = '';
    if (searchTerm === '') {
        searchResults.innerHTML = 'Please enter a search term.';
        return;
    }

    const filteredHymns = hymns.filter(hymn =>
        hymn.title.toLowerCase().includes(searchTerm) || hymn.number.toString() === searchTerm
    );

    if (filteredHymns.length === 0) {
        searchResults.innerHTML = 'No hymns found.';
    } else {
        filteredHymns.forEach(hymn => {
            const hymnElement = document.createElement('div');
            hymnElement.innerHTML = `<strong>#${hymn.number}</strong> - ${hymn.title}<br>${hymn.lyrics}`;
            searchResults.appendChild(hymnElement);
        });
    }
}
